require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SalestransactionsController do

  # This should return the minimal set of attributes required to create a valid
  # Salestransaction. As you add validations to Salestransaction, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "sdate" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SalestransactionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all salestransactions as @salestransactions" do
      salestransaction = Salestransaction.create! valid_attributes
      get :index, {}, valid_session
      assigns(:salestransactions).should eq([salestransaction])
    end
  end

  describe "GET show" do
    it "assigns the requested salestransaction as @salestransaction" do
      salestransaction = Salestransaction.create! valid_attributes
      get :show, {:id => salestransaction.to_param}, valid_session
      assigns(:salestransaction).should eq(salestransaction)
    end
  end

  describe "GET new" do
    it "assigns a new salestransaction as @salestransaction" do
      get :new, {}, valid_session
      assigns(:salestransaction).should be_a_new(Salestransaction)
    end
  end

  describe "GET edit" do
    it "assigns the requested salestransaction as @salestransaction" do
      salestransaction = Salestransaction.create! valid_attributes
      get :edit, {:id => salestransaction.to_param}, valid_session
      assigns(:salestransaction).should eq(salestransaction)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Salestransaction" do
        expect {
          post :create, {:salestransaction => valid_attributes}, valid_session
        }.to change(Salestransaction, :count).by(1)
      end

      it "assigns a newly created salestransaction as @salestransaction" do
        post :create, {:salestransaction => valid_attributes}, valid_session
        assigns(:salestransaction).should be_a(Salestransaction)
        assigns(:salestransaction).should be_persisted
      end

      it "redirects to the created salestransaction" do
        post :create, {:salestransaction => valid_attributes}, valid_session
        response.should redirect_to(Salestransaction.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved salestransaction as @salestransaction" do
        # Trigger the behavior that occurs when invalid params are submitted
        Salestransaction.any_instance.stub(:save).and_return(false)
        post :create, {:salestransaction => { "sdate" => "invalid value" }}, valid_session
        assigns(:salestransaction).should be_a_new(Salestransaction)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Salestransaction.any_instance.stub(:save).and_return(false)
        post :create, {:salestransaction => { "sdate" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested salestransaction" do
        salestransaction = Salestransaction.create! valid_attributes
        # Assuming there are no other salestransactions in the database, this
        # specifies that the Salestransaction created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Salestransaction.any_instance.should_receive(:update).with({ "sdate" => "MyString" })
        put :update, {:id => salestransaction.to_param, :salestransaction => { "sdate" => "MyString" }}, valid_session
      end

      it "assigns the requested salestransaction as @salestransaction" do
        salestransaction = Salestransaction.create! valid_attributes
        put :update, {:id => salestransaction.to_param, :salestransaction => valid_attributes}, valid_session
        assigns(:salestransaction).should eq(salestransaction)
      end

      it "redirects to the salestransaction" do
        salestransaction = Salestransaction.create! valid_attributes
        put :update, {:id => salestransaction.to_param, :salestransaction => valid_attributes}, valid_session
        response.should redirect_to(salestransaction)
      end
    end

    describe "with invalid params" do
      it "assigns the salestransaction as @salestransaction" do
        salestransaction = Salestransaction.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Salestransaction.any_instance.stub(:save).and_return(false)
        put :update, {:id => salestransaction.to_param, :salestransaction => { "sdate" => "invalid value" }}, valid_session
        assigns(:salestransaction).should eq(salestransaction)
      end

      it "re-renders the 'edit' template" do
        salestransaction = Salestransaction.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Salestransaction.any_instance.stub(:save).and_return(false)
        put :update, {:id => salestransaction.to_param, :salestransaction => { "sdate" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested salestransaction" do
      salestransaction = Salestransaction.create! valid_attributes
      expect {
        delete :destroy, {:id => salestransaction.to_param}, valid_session
      }.to change(Salestransaction, :count).by(-1)
    end

    it "redirects to the salestransactions list" do
      salestransaction = Salestransaction.create! valid_attributes
      delete :destroy, {:id => salestransaction.to_param}, valid_session
      response.should redirect_to(salestransactions_url)
    end
  end

end
